import * as assert from 'node:assert/strict'
import * as childProcess from 'node:child_process'

const origin = process.env.INCUR_INSTALLER_SMOKE_ORIGIN ?? 'https://incur.app'
const repository = process.env.INCUR_INSTALLER_SMOKE_REPOSITORY

assert.match(origin, /^https:\/\/[A-Za-z0-9.-]+(?::\d+)?$/)
assert.match(repository ?? '', /^[A-Za-z0-9_.-]{1,39}\/[A-Za-z0-9_.-]{1,100}$/)

const [organization, name] = repository.split('/')
assert.notEqual(organization, '.')
assert.notEqual(organization, '..')
assert.notEqual(name, '.')
assert.notEqual(name, '..')

const shell = `https://github.com/${organization}/${name}/releases/latest/download/install.sh`
const powershell = `https://github.com/${organization}/${name}/releases/latest/download/install.ps1`
const encodedOrganization = `%${organization.charCodeAt(0).toString(16).padStart(2, '0')}${organization.slice(1)}`

assertRedirect(`/${organization}/${name}`, shell)
assertRedirect(`/${organization}/${name}/install.ps1`, powershell)
assertRedirect(`/${encodedOrganization}/${name}`, shell)
assertRedirect(`/ignored/../${organization}/${name}`, shell)
assertRedirect(`/${organization}//${name}`, shell)
assertNotFound(`/${organization}%2Fattacker/${name}`)
assertNotFound(`/${organization}\\${name}`)
assertMethodNotAllowed(`/${organization}/${name}`)

const shellInstaller = download(shell)
const powershellInstaller = download(powershell)
const shellVersion = assertShellInstaller(shellInstaller)
const powershellVersion = assertPowerShellInstaller(powershellInstaller)
assert.equal(shellVersion, powershellVersion)

const versionedShell = `https://github.com/${organization}/${name}/releases/download/v${shellVersion}/install.sh`
const versionedPowershell = `https://github.com/${organization}/${name}/releases/download/v${shellVersion}/install.ps1`
const encodedVersion = shellVersion.replace('.', '%2E')

assertRedirect(`/${organization}/${name}@${shellVersion}`, versionedShell)
assertRedirect(`/${organization}/${name}@${shellVersion}/install.ps1`, versionedPowershell)
assertRedirect(`/${organization}/${name}@${encodedVersion}`, versionedShell)
assertNotFound(`/${organization}/${name}%40${shellVersion}`)
assertNotFound(`/${organization}/${name}@v${shellVersion}`)
assertNotFound(`/${organization}/${name}@${shellVersion}%2Fevil`)
assertNotFound(`/${organization}/${name}@${shellVersion}%0D`)
assertMethodNotAllowed(`/${organization}/${name}@${shellVersion}`)
assert.equal(download(versionedShell), shellInstaller)
assert.equal(download(versionedPowershell), powershellInstaller)

console.log(`Verified ${origin}/${repository} at latest and ${shellVersion}`)

function assertCommon(response) {
  assert.equal(response.headers.get('access-control-allow-origin'), undefined)
  assert.equal(response.headers.get('cache-control'), 'no-store')
  assert.equal(response.headers.get('referrer-policy'), 'no-referrer')
  assert.equal(response.headers.get('set-cookie'), undefined)
  assert.equal(response.headers.get('x-content-type-options'), 'nosniff')
  assert.equal(response.headers.get('x-robots-tag'), 'noindex, nofollow, noarchive')
}

function assertMethodNotAllowed(path) {
  const response = request({ method: 'POST', path })
  assertCommon(response)
  assert.equal(response.status, 405)
  assert.equal(response.headers.get('allow'), 'GET, HEAD')
  assert.equal(response.headers.get('location'), undefined)
}

function assertNotFound(path) {
  const response = request({ method: 'GET', path })
  assertCommon(response)
  assert.equal(response.status, 404)
  assert.equal(response.headers.get('allow'), undefined)
  assert.equal(response.headers.get('location'), undefined)
}

function assertRedirect(path, location) {
  const response = request({ method: 'GET', path })
  assertCommon(response)
  assert.equal(response.status, 307)
  assert.equal(response.headers.get('allow'), undefined)
  assert.equal(response.headers.get('location'), location)
}

function assertPowerShellInstaller(installer) {
  assert.ok(installer.length > 1_000)
  assert.ok(installer.startsWith('# Generated by Incur. Do not edit.\n'))
  assert.ok(installer.includes(`$repository = '${repository}'`))
  assert.ok(
    installer.includes('$baseUrl = "https://github.com/$repository/releases/download/$tag"'),
  )
  assert.ok(installer.includes("Get-FileHash -LiteralPath $archive -Algorithm 'SHA256'"))
  assert.ok(installer.includes('[IO.File]::Replace($staged, $destination, $null, $true)'))
  assert.ok(installer.endsWith('}\n'))

  const version = installer.match(
    /\n\$tag = 'v((?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*))'\n/,
  )?.[1]
  assert.ok(version)
  return version
}

function assertShellInstaller(installer) {
  assert.ok(installer.length > 1_000)
  assert.ok(installer.startsWith('#!/bin/sh\n# Generated by Incur. Do not edit.\n'))
  assert.ok(installer.includes(`repository='${repository}'`))
  assert.ok(installer.includes('base_url="https://github.com/$repository/releases/download/$tag"'))
  assert.ok(installer.includes('SHA-256 checksum mismatch for $asset'))
  assert.ok(installer.includes('mv -f "$staged" "$destination"'))
  assert.ok(installer.endsWith('esac\n'))

  const version = installer.match(
    /\ntag='v((?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*))'\n/,
  )?.[1]
  assert.ok(version)

  const syntax = childProcess.spawnSync('sh', ['-n'], {
    encoding: 'utf8',
    input: installer,
  })
  assert.equal(syntax.status, 0, syntax.stderr)
  return version
}

function download(location) {
  return childProcess.execFileSync(
    'curl',
    [
      '--fail',
      '--location',
      '--max-filesize',
      '1048576',
      '--max-time',
      '30',
      '--proto',
      '=https',
      '--proto-redir',
      '=https',
      '--show-error',
      '--silent',
      location,
    ],
    {
      encoding: 'utf8',
      maxBuffer: 1_100_000,
    },
  )
}

function request(options) {
  const output = childProcess.execFileSync(
    'curl',
    [
      '--connect-timeout',
      '5',
      '--dump-header',
      '-',
      '--http1.1',
      '--max-time',
      '15',
      '--output',
      '/dev/null',
      '--path-as-is',
      '--request',
      options.method,
      '--show-error',
      '--silent',
      `${origin}${options.path}`,
    ],
    { encoding: 'utf8' },
  )
  const blocks = output.trim().split(/\r?\n\r?\n/)
  const block = blocks.findLast((value) => value.startsWith('HTTP/'))
  assert.ok(block, `Missing HTTP response for ${options.path}`)

  const [statusLine, ...lines] = block.split(/\r?\n/)
  const status = Number(statusLine.match(/^HTTP\/\S+ (\d{3})/)?.[1])
  assert.ok(Number.isInteger(status), `Missing HTTP status for ${options.path}`)

  const headers = new Map()
  for (const line of lines) {
    const separator = line.indexOf(':')
    if (separator === -1) continue
    headers.set(line.slice(0, separator).toLowerCase(), line.slice(separator + 1).trim())
  }
  return { headers, status }
}
